### ISSUE TITLE
[bug] TWSavedQueries result popup disappear in neovim 0.10

### ISSUE THREAD

**Issue by simonlearnscoding** [huantrinh1802/m_taskwarrior_d.nvim#36]
when I run :TWSavedQueries it opens a popup that closes itself within like 50ms

Steps to Reproduce:

I'm on Linux Pop_os
Neovim 0.10

**Comment by huantrinh1802** [comment]
Could you check if there is a file called `m_taskwarrior_d.json` in `~/.local/share/nvim/`?
If not, can you add this by running
```
touch ~/.local/share/nvim/m_taskwarrior_d.json
```
and then add this into the file
```json
{"saved_queries": {"name_max_length": 0,"data": []}}
```

**Comment by simonlearnscoding** [comment]
Hey yes the file was there, I changed name_max_length to 0 but it didnt change anything. The first popup with the queries shows up but when I want to open a query nothing happens unfortunately

**Comment by huantrinh1802** [comment]
can you share the query that you want to open?
also, side note, the result will be in a float window, which is dismissed if you move the cursor (similar to lsp definition float window)

**Comment by simonlearnscoding** [comment]
sure these are my queries

[today] | [planned:today]
[nvim] | [+nvim]

**Comment by huantrinh1802** [comment]
can you try to use this 
```
[today] | | planned:today
[nvim] | +nvim
```
The reason for the second pipe (|) in the first is because I need a way to seperate Taskwarrior's filters and reports. And `planned:today` is the report.

**Comment by simonlearnscoding** [comment]
today]| | planned:tod
nvim  | +nvim

changed it to this, still not working unfortunately, the popup closes immediately, not sure why

**Comment by huantrinh1802** [comment]
I may need to test it in neovim 0.10. By the way, is there any error? You can check it in `:messages`

**Comment by huantrinh1802** [comment]
@simonlearnscoding In v0.5.x, I will remove the `CursorMoved` event that will close the popup. The new approach will be:

- Enter the popup by default.
- You can either `:q` or `q` to exit. I tested and it seems more intuitive

Let me know what do you think

**Comment by simonlearnscoding** [comment]
yes I would also add C-c to exit, I agree that it would be more intuitive! Let me know when I can pull the update. 

Also I created a PR if you want to have a look at it :)
I added an optional $endquery delimiter that will stop the query in case you want to have multiple queries in a buffer.

I see that you have js and python as todos in your roadmap - personally I think it would be very helpful to have those. do you have discord? We could sync up one day and discuss how I could help you achieve it

**Comment by huantrinh1802** [comment]
Noted: would be possible.

Regarding the PR, I left a comment there. Let's discuss it there.

I initially thought directly parse the JSDoc or Docstring like how it is working with Markdown but I don't think its feasible as you will need to commit it to Git. I need to brainstorm about this. I do have discords but for now, I will open the discuss section.
