### ISSUE TITLE
Inline properties don't work

### ISSUE THREAD

**Issue by simonlearnscoding** [huantrinh1802/m_taskwarrior_d.nvim#43]
for example I created a custom property planned: tod | tw | tm

- [ ]  meeting planned:tw $id{8672ba37-8f3a-4995-9d49-18970409073d}

the planned property won't sync. 
Although I don't know if you can really count it as a bug because I'm not sure if it's part of this projects scope

**Comment by huantrinh1802** [comment]
Can you provide how would you use it directly with the CLI? I am not familiar with this usage (this is probably why it is not implemented yet :))

**Comment by huantrinh1802** [comment]
Why don't you use query task for this? 

```
# Routine $query{priority:H planned:today}

- [ ] Workout
- [ ] Cook dinner

```

It might be inconvenient to type the header but I think it would work.

In case that you only want to add one task on the fly. Try `:TWRun add Workout priority`

**Comment by simonlearnscoding** [comment]
no no thats not what I mean, not talking about queries but syncing a task you created that has a custom property.

if I write a new line like this
- [ ] task planned:today

then the task gets synced but the property planned:today won't get synced or concealed

**Comment by huantrinh1802** [comment]
To confirm, the ideal output is that the `planned:today` will be added to the task and removed/concealed from the view?

With this 
```markdown
# Routine $query{priority:H planned:today}

- [ ] Workout
- [ ] Cook dinner
```
and then run `TWSyncTasks`, you can achieve the same result. `Workout` and `Cook dinner` will have `priority:H` and `planned:today` added to both.

**Comment by simonlearnscoding** [comment]
Okay sure I will use queries as a workaround thank you!

**Comment by huantrinh1802** [comment]
Closing it as it will not be in the plugin's roadmap
