### ISSUE TITLE
Missing closed bracket

### ISSUE THREAD

**Issue by simonlearnscoding** [huantrinh1802/m_taskwarrior_d.nvim#48]
Did you forget to close a bracket by chance? I am getting the following error

![image](https://github.com/huantrinh1802/m_taskwarrior_d.nvim/assets/40177876/dd5989dd-02a3-4cc2-bac8-ddf830202abc)

**Comment by simonlearnscoding** [comment]
update: you forgot to add a , at line 15, that should fix it. 

![image](https://github.com/huantrinh1802/m_taskwarrior_d.nvim/assets/40177876/8e202cd8-608f-4a20-bc2c-d998d3cb0565)

**Comment by huantrinh1802** [comment]
Whoops, thank you
