### ISSUE TITLE
Allow to change the pattern of the task from `- [ ]` to more flexible pattern

### ISSUE THREAD

**Issue by aleprovencio** [huantrinh1802/m_taskwarrior_d.nvim#62]
Hi!

What I mean is something like `Taskwiki` does, here is a quote from their `Readme`:

> Taskwiki only handles check lists that use the asterisk *. All other lists, i.e. those written with a hyphen - or a pound sign # as well as ordered lists, are left alone. This allows you to define plain lists and even vimwiki check lists that are unrelated to Taskwarrior.

Can we have this feature on `m_taskwarrior_d`?

**Comment by huantrinh1802** [comment]
Yes, actually the current implementation is opposite of what Taskwiki does. I only match `- [ ]` and ignore the rest. If necessary, we can add support for other lists syntax as it is just a regex pattern.

**Comment by huantrinh1802** [comment]
All good. I will leave this open for adding the ability to change the pattern

**Comment by jdrupal-dev** [comment]
Any updates on this?
Would be a nice improvement to how this plugin works with neorg, the norg checkbox uses the `- ( )` format.

**Comment by huantrinh1802** [comment]
Hi @jdrupal-dev, I have not prioritised this yet. However, since I think it might be a quick refactoring and I am in a middle of a massive cycle of development at my main job, I might be able to sneak it in around mid July.

Even then, a quick disclaimer, this will only add support for (`-`,`*`) (`( )`, `[ ]`). I cannot guarantee the plugin's compatibility with neorg/org mode.

**Comment by jdrupal-dev** [comment]
Hi @huantrinh1802,
Cool, looking forward to that :)

Apart from a few oddities, such as not being able to mark a task as done with -[x] and the conceil icons being displayed 3 times, it generally works quite nicely with .norg files.

I have added this autocmd to sync tasks when entering .norg files:
```
-- Be cautious: it may be slow to open large files, because it scan the whole buffer.
vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost" }, {
  group = vim.api.nvim_create_augroup("TWTask", { clear = true }),
  pattern = "*.norg",
  callback = function()
    vim.cmd("TWSyncTasks")
    vim.cmd("TWBufQueryTasks")
    vim.cmd("w")
  end,
})
```

![image](https://github.com/huantrinh1802/m_taskwarrior_d.nvim/assets/13871894/275702df-e682-451a-84b0-3e07b9af2b54)

**Comment by jdrupal-dev** [comment]
@huantrinh1802 I have opened a PR that allows configuring checkbox prefix and suffix.
https://github.com/huantrinh1802/m_taskwarrior_d.nvim/pull/64
