### ISSUE TITLE
Feature Request: Better Hiding of plugin queries and task ids

### ISSUE THREAD

**Issue by fullstopslash** [huantrinh1802/m_taskwarrior_d.nvim#66]
So this was something that always bothered me about taskwiki as well. While i get that queries for lists and task ids are the core of the plugin, and legitimately the thing that makes a plugin like this useful. I think it would be absolutely amazing if these could get hidden in the rendered document instead of fussing up the page with all the code. Thankfully markdown has a comment feature, and all the data could be wrapped in a comment tag! 

So what I'm envisioning, instead of this:

```markdown
##Header $query{+PENDING}
```

```markdown
##Header <!-- $query{+PENDING} -->
```

Ideally this would be for any custom tag that this plugin implements.

**Comment by huantrinh1802** [comment]
Hey @fullstopslash, absolutely love this. It also bothers me when I tried to read them in Obsidian but I didn't think of using comment :'(. This is likely to be the next feature.

**Comment by fullstopslash** [comment]
That's so exciting! Thank you! So for instance, markdownlint handles it like this: 

```markdown
Some text <!-- markdownlint-disable-line MD003 -->
```

You could do it any number of ways, but perhaps it'd be nice if the comment also gave an indication as to what tool was acting upon it!

**Comment by huantrinh1802** [comment]
My current plan is to add something like https://github.com/huantrinh1802/m_taskwarrior_d.nvim/pull/64 
We will have:
- `comment_prefix = "<!--"`
- `comment_suffix = "-->"`

I also plan to extend the pattern for concealing to support the `comment_*`

<img width="350" alt="Screenshot 2024-07-20 at 10 53 38 AM" src="https://github.com/user-attachments/assets/ee5acc95-4feb-4fed-b3c0-7fc5a596536e">

so it will look nice on Neovim and markdown preview
