### ISSUE TITLE
uuid is not properly detected resulting in a infinite task

### ISSUE THREAD

**Issue by DeadlySquad13** [huantrinh1802/m_taskwarrior_d.nvim#70]
Hello, thanks for your plugin!
Unfortunately, I've encountered bug:
1. Write `- [ ] Test`
2. TWSyncTasks
3. uuid is appended to the task: `- [ ] Test $id{...}`
4. TWSyncTasks
5. uuid is appended once again: `- [ ] Test $id{...} $id{...}`
6. ... and so on...

In the taskwarrior I see that each task is considered a new one. So uuid is not detected and after it's appended by this plugin a new one created as many times as we run `TWSyncTasks`.
```
105 1min  Test                                                                                                                         0
106 40s   Test {54c8ed14-7163-448b-a0be-5c8b34188944}                                                                                  0
107 31s   Test {54c8ed14-7163-448b-a0be-5c8b34188944} {3d97278a-0eef-4fca-82cb-e6aa703afb5d}                                           0
108 26s   Test {54c8ed14-7163-448b-a0be-5c8b34188944} {3d97278a-0eef-4fca-82cb-e6aa703afb5d} {6d3adc35-248f-44b8-a4fe-b60b431de688}    0
```

I tried to dig into source code to fix this problem. As for me, problem lies in id_part_pattern and how it accounts comment strings (that IMHO also doesn't work correctly - I don't see a comment string added to the id part).

I placed print statement in a `add_or_sync_task` function:
```lua
  local _, uuid = string.match(line, M.id_part_pattern.lua)
  print(uuid, M.id_part_pattern.lua)
  if uuid == nil then
```

And got following results (during `TWSyncTasks` on a second and fourth steps):
```
nil (<!%-%- (%$id{(%x*-%x*-%x*-%x*-%x*)}) %-%-%>)
nil (<!%-%- (%$id{(%x*-%x*-%x*-%x*-%x*)}) %-%-%>)
```

As you can see uuid is always nil. And pattern has comment strings while I didn't pass it to the config.
It seems they're not inserted properly when I run the command.

I tried commenting id part manually (`- [ ] Test5 <!-- $id{...} -->`) and got proper id:
```
$id{6ba95418-c21a-4c58-a0d5-870c14f42bc3} (<!%-%- (%$id{(%x*-%x*-%x*-%x*-%x*)}) %-%-%>)
```
but it was immediately overwritten by plugin and I was left with the task without comment (`- [ ] Test5 $id{...}`). On next run it of course yielded the same error:
```
nil (<!%-%- (%$id{(%x*-%x*-%x*-%x*-%x*)}) %-%-%>)
```

I tried setting an empty comment string but got the same buggy behaviour. The pattern seemed incorrect too (notice the space between `(`):
```
nil ( (%$id{(%x*-%x*-%x*-%x*-%x*)}) )
nil ( (%$id{(%x*-%x*-%x*-%x*-%x*)}) )
```

Hope you help resolve this issue! I have just installed this plugin so I'm still not 100% sure I understand how everything should work ideally and I'm confused why this bug wasn't noticed yet - what if it's mistake on my part... Anyway, I'll try to assist as much as possible!

**Comment by huantrinh1802** [comment]
Hey @DeadlySquad13, thanks for raising an issue (and being early adapter). Yes, definitely a bug. Apology for the issue, I was eager to release this version with comments support. I will likely to release a fix for this ASAP

**Comment by huantrinh1802** [comment]
A bonus if you want to remove the duplicated entries, you can try `task modified.after:today-[number of hours]h done` or `delete`

**Comment by DeadlySquad13** [comment]
@huantrinh1802, thanks for the quick response! The bug is fixed on newer version. But the comment is still not added - you have to add it manually after first sync. After that comment works fine. Is it intended behaviour? As for me, comment should be inserted after first `TWSyncTasks` along with uuid. For example, if you run:
- `- [ ] Test`
- `TWSyncTasks`

You get a `- [ ] Test $id{...}`. Of course, if you run `TWSyncTasks` again, it will not detect uuid properly (because it lacks comments) and add a one more uuid. So I think the result should be `- [ ] Test <!-- $id{...} -->` instead if the comment_prefix and comment_suffix are set.

**Comment by huantrinh1802** [comment]
Yup, good catch. I totally missed that.
