### ISSUE TITLE
Bigger font screenshots

### ISSUE THREAD

**Issue by aniketgm** [huantrinh1802/m_taskwarrior_d.nvim#78]
## Description

Firstly, thank you for this plugin. I was about to write one, since I recently started with TW and I wanted something from nvim.
Thanks for saving some efforts on my end. Starred.

Sorry if this seems a silly question. If it does, feel free to reply `No` and close it. I would not mind at all.
So, the screen shots seem too much small and since I also have glasses, it's difficult to see how this works.
If its not much of a work, can we have screenshots with bigger fonts please ?

**Comment by huantrinh1802** [comment]
Hey @aniketgm, thanks for the feedback and spending time using the plugin. As this is not urgent, I will not prioritise this. But I do have a plan to improve the README at some point.
