### ISSUE TITLE
Typo in default config?

### ISSUE THREAD

**Issue by lxgreen** [huantrinh1802/m_taskwarrior_d.nvim#85]
Hey, I think you have typo in `init.lua`:

the [_config exposes](https://github.com/huantrinh1802/m_taskwarrior_d.nvim/blob/fbb9ebb78053b2d8a26188d8b19a33ab7bf5a71f/lua/m_taskwarrior_d/init.lua#L22) `file_patterns` while [other places](https://github.com/huantrinh1802/m_taskwarrior_d.nvim/blob/fbb9ebb78053b2d8a26188d8b19a33ab7bf5a71f/lua/m_taskwarrior_d/init.lua#L698) refer to `file_pattern`.

Since this autocmd addition, my nvim freezes on _any_ buffer switch. Not sure 100% if this is the exact reason, but when I turn the `m_taskwarrior_d` down, the editor does not freeze.

**Comment by huantrinh1802** [comment]
Hi @lxgreen, thanks for spotting the issue. I released 0.8.3 to address the typo. Can you get back if the issue still persists? Thanks

**Comment by lxgreen** [comment]
hey @huantrinh1802 

the issue is solved, thanks!
